spring.application.name=sistema-biblioteca

#Configura��o do Servidor

server.port=8080

#Configura��o do banco H2(em mem�ria)

#Define a URL de conexao com o banco, especifica o tipo de banco, identifica o banco H2, modo em memoria, nome qualquer do banco.

spring.datasource.url=jdbc:h2:mem:testdb

#Driver faz a ponte entre h2 e java para mostrar ao usuario(traduz para linguagem java as informacoes do bando de dados, o Driver pega a informa��o e leva

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=lucas
spring.datasource.password=123


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console